version: '3.4'

services:
  tcc.identity.api:
    image: ${DOCKER_REGISTRY-}tcc-identity-api
    container_name: tcc-identity-api-container
    build:
      context: .
      dockerfile: src/Tcc.Identity.Api/Dockerfile
    depends_on:
        mysql_database:
            condition: service_healthy
  mysql_database:
    image: mysql:8.0
    container_name: mysql-database-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  redis_database:
    image: redis:7.2.4
    container_name: redis-database-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/data:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=123123123
      - REDIS_PORT=6379
      - REDIS_DATABASES=16